### ISSUE TITLE
Can not login with https or ipv6

### ISSUE THREAD

**Issue by be-engineer** [Radiokot/photoprism-android-client#157]
**What is wrong?**
When I usb https and ipv6 domain login, I got some error message as follows.
![image](https://github.com/user-attachments/assets/f600c2ad-b5bd-4e97-bc4d-bd6f026fd582)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Model: xiaomi redmi note9
 - Android version: MiUI 13

**Additional context**

**Comment by Radiokot** [comment]
The app can't establish a secure connection to your library because of SSL misconfiguration. There may not be a corresponding root certificate on the phone, or the server certificate chain may be incomplete, or you've specified the wrong port in the library root URL. Check if the library is accessible from a phone browser with the same URL. Then run an online [SSL check](https://www.geocerts.com/ssl-checker), which may also point out the issue. If you use a self-signed certificate, follow [this checklist](https://github.com/Radiokot/photoprism-android-client/issues/130#issuecomment-1962339179). The app won't work with PhotoPrism default TLS
